# 젠킨스 서버 
# docker run -d -p 8180:8080 -v /var/jenkins_home --name jenkins -u root jenkins/jenkins:jdk11

version: '3.9'

services:
  jenkins: 
    image: parkingplace/jenkins-docker-custom:latest
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
    user: root
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins/config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always